# Runs backend and frontend services together

services:
 backend:
  build:
   context: .
   dockerfile: backend/Dockerfile
  ports:
   - "8002:8002"

 frontend:
  build: ./frontend
  ports:
   - "3000:3000"